apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-data-collector
spec:
  selector:
    matchLabels:
      app: k8s-data-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-data-collector
    spec:
      containers:
      - name: k8s-data-collector
        # image: docker.io/talhaabdurrahman/k8s-data-collector:latest
        image: docker.io/talhaabdurrahman/kijiji-collector:v2
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-data-collector
  labels:
    app: k8s-data-collector
spec:
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: k8s-data-collector
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-data-collector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-data-collector
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
